package com.hll.test.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table taskinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TaskInfo {
    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.taskID
     *
     * @mbg.generated
     */
    private Integer taskID;

    /**
     * Database Column Remarks:
     *   任务类型 0需求 1开发 2测试 3bug
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.taskType
     *
     * @mbg.generated
     */
    private Integer taskType;

    /**
     * Database Column Remarks:
     *   流程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.processID
     *
     * @mbg.generated
     */
    private Integer processID;

    /**
     * Database Column Remarks:
     *   领导id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.leaderID
     *
     * @mbg.generated
     */
    private Integer leaderID;

    /**
     * Database Column Remarks:
     *   执行者ids(用逗号拼接)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.workerIDs
     *
     * @mbg.generated
     */
    private String workerIDs;

    /**
     * Database Column Remarks:
     *    任务状态(0 已建议 1活动的 2已解决 3已关闭)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.taskState
     *
     * @mbg.generated
     */
    private Integer taskState;

    /**
     * Database Column Remarks:
     *   任务级别(0 轻 1中 2重)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.taskLevel
     *
     * @mbg.generated
     */
    private Integer taskLevel;

    /**
     * Database Column Remarks:
     *   提问编号(用逗号隔开)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskinfo.reportIDs
     *
     * @mbg.generated
     */
    private String reportIDs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.taskID
     *
     * @return the value of taskinfo.taskID
     *
     * @mbg.generated
     */
    public Integer getTaskID() {
        return taskID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.taskID
     *
     * @param taskID the value for taskinfo.taskID
     *
     * @mbg.generated
     */
    public void setTaskID(Integer taskID) {
        this.taskID = taskID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.taskType
     *
     * @return the value of taskinfo.taskType
     *
     * @mbg.generated
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.taskType
     *
     * @param taskType the value for taskinfo.taskType
     *
     * @mbg.generated
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.processID
     *
     * @return the value of taskinfo.processID
     *
     * @mbg.generated
     */
    public Integer getProcessID() {
        return processID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.processID
     *
     * @param processID the value for taskinfo.processID
     *
     * @mbg.generated
     */
    public void setProcessID(Integer processID) {
        this.processID = processID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.leaderID
     *
     * @return the value of taskinfo.leaderID
     *
     * @mbg.generated
     */
    public Integer getLeaderID() {
        return leaderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.leaderID
     *
     * @param leaderID the value for taskinfo.leaderID
     *
     * @mbg.generated
     */
    public void setLeaderID(Integer leaderID) {
        this.leaderID = leaderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.workerIDs
     *
     * @return the value of taskinfo.workerIDs
     *
     * @mbg.generated
     */
    public String getWorkerIDs() {
        return workerIDs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.workerIDs
     *
     * @param workerIDs the value for taskinfo.workerIDs
     *
     * @mbg.generated
     */
    public void setWorkerIDs(String workerIDs) {
        this.workerIDs = workerIDs == null ? null : workerIDs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.taskState
     *
     * @return the value of taskinfo.taskState
     *
     * @mbg.generated
     */
    public Integer getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.taskState
     *
     * @param taskState the value for taskinfo.taskState
     *
     * @mbg.generated
     */
    public void setTaskState(Integer taskState) {
        this.taskState = taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.taskLevel
     *
     * @return the value of taskinfo.taskLevel
     *
     * @mbg.generated
     */
    public Integer getTaskLevel() {
        return taskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.taskLevel
     *
     * @param taskLevel the value for taskinfo.taskLevel
     *
     * @mbg.generated
     */
    public void setTaskLevel(Integer taskLevel) {
        this.taskLevel = taskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskinfo.reportIDs
     *
     * @return the value of taskinfo.reportIDs
     *
     * @mbg.generated
     */
    public String getReportIDs() {
        return reportIDs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskinfo.reportIDs
     *
     * @param reportIDs the value for taskinfo.reportIDs
     *
     * @mbg.generated
     */
    public void setReportIDs(String reportIDs) {
        this.reportIDs = reportIDs == null ? null : reportIDs.trim();
    }
}