package com.hll.test.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table userinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserInfo {
    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userID
     *
     * @mbg.generated
     */
    private Integer userID;

    /**
     * Database Column Remarks:
     *   角色编号  0需求人员,1开发人员 2测试人员 3超级管理员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.roleID
     *
     * @mbg.generated
     */
    private Integer roleID;

    /**
     * Database Column Remarks:
     *   是否为领导 0不是 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.isLeader
     *
     * @mbg.generated
     */
    private Integer isLeader;

    /**
     * Database Column Remarks:
     *   密码 最多20位 md5加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户名,显示名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userID
     *
     * @return the value of userinfo.userID
     *
     * @mbg.generated
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userID
     *
     * @param userID the value for userinfo.userID
     *
     * @mbg.generated
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.roleID
     *
     * @return the value of userinfo.roleID
     *
     * @mbg.generated
     */
    public Integer getRoleID() {
        return roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.roleID
     *
     * @param roleID the value for userinfo.roleID
     *
     * @mbg.generated
     */
    public void setRoleID(Integer roleID) {
        this.roleID = roleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.isLeader
     *
     * @return the value of userinfo.isLeader
     *
     * @mbg.generated
     */
    public Integer getIsLeader() {
        return isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.isLeader
     *
     * @param isLeader the value for userinfo.isLeader
     *
     * @mbg.generated
     */
    public void setIsLeader(Integer isLeader) {
        this.isLeader = isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userName
     *
     * @return the value of userinfo.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userName
     *
     * @param userName the value for userinfo.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}