package com.hll.test.dao;

import java.util.List;
import java.util.Map;

import com.hll.test.dao.domain.ProcessInfo;

public interface ProcessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer processID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    int insert(ProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    int insertSelective(ProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    ProcessInfo selectByPrimaryKey(Integer processID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProcessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table processinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProcessInfo record);

    List<Map<String,Object>> selectAllPage(Map<String, Object> map);
}