package com.hll.test.dao;

import java.util.List;
import java.util.Map;

import com.hll.test.dao.domain.ReportInfo;

public interface ReportInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reportID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    int insert(ReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    int insertSelective(ReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    ReportInfo selectByPrimaryKey(Integer reportID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportInfo record);

    List<Map<String, Object>> selectAllPage(Map<String, Object> map);
}